#remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
theme: jekyll-theme-minimal
description: Petroleum engineer turned data scientist with expertise in reservoir analysis, drilling optimization, and production management. Certified in data science with skills in machine learning and big data analytics. Passionate about leveraging data to drive insights and innovation in the energy industry. Let's connect and explore opportunities to collaborate!
title: Daniall T. Qureshi
logo: assets/img/laptop.jpg
