#remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
theme: jekyll-theme-minimal
description: Passionate about leveraging data to drive insights and innovation in the energy industry.
title: Daniall T. Qureshi
logo: assets/img/profile.png
